const express = require('express')
const router = express.Router()
const userRouter = require('../../module/User/user.route')
const adminRouter = require('../../module/Admin/admin.route')
const sidebarRouter = require('../../module/Sidebar/sidebar.route')
const permissionRouter = require('../../module/Permission/permission.route')
const roleRouter = require('../../module/Role/role.route')
const categoryRouter = require('../../module/Category/category.route')
const subcategoryRouter = require('../../module/Subcategory/subcategory.route')
const subSubcategoryRouter = require('../../module/SubSubcategory/subSubcategory.route')
const taxRouter = require('../../module/Tax/tax.route')
const brandRouter = require('../../module/Brands/brand.route')
const productRouter = require('../../module/Product/product.route')
const unitRouter = require('../../module/Unit/unit.route')
const bannerRouter = require('../../module/Banner/banner.route')
const customerRouter = require('../../module/Customer/customer.route')
const queryRouter = require('../../module/Query/query.route')
const servicePartnerRouter = require('../../module/ServicePartner/servicePartner.route')
const couponsRouter = require('../../module/Coupons/coupons.route')
const cartRouter = require('../../module/Cart/cart.route')
const orderRouter = require('../../module/Order/order.route')
const cmsRouter = require('../../module/CMS/cms.route')
const reportRouter = require('../../module/Report/report.route')
const reviewRouter = require('../../module/Review/review.route')

router.use('/user', userRouter)
router.use('/admin', adminRouter)
router.use('/sidebar', sidebarRouter)
router.use('/permission', permissionRouter)
router.use('/role', roleRouter)
router.use('/category', categoryRouter)
router.use('/subcategory', subcategoryRouter)
router.use('/sub-subcategory', subSubcategoryRouter)
router.use('/tax', taxRouter)
router.use('/brand', brandRouter)
router.use('/product', productRouter)
router.use('/unit', unitRouter)
router.use('/banner', bannerRouter)
router.use('/customer', customerRouter)
router.use('/query', queryRouter)
router.use('/service-partner', servicePartnerRouter)
router.use('/coupon', couponsRouter)
router.use('/cart', cartRouter)
router.use('/order', orderRouter)
router.use('/cms', cmsRouter)
router.use('/report', reportRouter)
router.use('/review', reviewRouter)

module.exports = router
