const express = require('express')
const router = express.Router()
const userRouter = require('../../module/User/user.route')
const adminRouter = require('../../module/Admin/admin.route')
const sidebarRouter = require('../../module/Sidebar/sidebar.route')
const permissionRouter = require('../../module/Permission/permission.route')
const roleRouter = require('../../module/Role/role.route')
const categoryRouter = require('../../module/Category/category.route')
const subcategoryRouter = require('../../module/Subcategory/subcategory.route')
const subSubcategoryRouter = require('../../module/SubSubcategory/subSubcategory.route')
const taxRouter = require('../../module/Tax/tax.route')
const brandRouter = require('../../module/Brands/brand.route')
const productRouter = require('../../module/Product/product.route')
const unitRouter = require('../../module/Unit/unit.route')

router.use('/user', userRouter)
router.use('/admin', adminRouter)
router.use('/sidebar', sidebarRouter)
router.use('/permission', permissionRouter)
router.use('/role', roleRouter)
router.use('/category', categoryRouter)
router.use('/subcategory', subcategoryRouter)
router.use('/sub-subcategory', subSubcategoryRouter)
router.use('/tax', taxRouter)
router.use('/brand', brandRouter)
router.use('/product', productRouter)
router.use('/unit', unitRouter)

module.exports = router
